config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts

  root "store#index", as: "store_index"
  get "cart/modal", to: "carts#modal", as: :cart_modal
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy


  def total_price
    line_items.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end


  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item.present?
      current_item.quantity+=1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    if session[:cart_id] == @cart.id
      @cart.destroy!
      session[:cart_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is currently empty." }
      format.json { head :no_content }
    end
  end

  def modal
    @cart = Cart.find_by(id: session[:cart_id])
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid Cart #{params[:id]}"
      redirect_to store_index_url, notice: "Invalid Cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>" class="w-full my-5 space-y-5">
    <% if cart.line_items.any? %>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">   
        <div class="lg:col-span-2 space-y-4">
            <% cart.line_items.each do |line_item| %>
              <div class="bg-white p-5 rounded-lg shadow-md flex flex-col items-start md:items-start">
                    <h2 class="font-semibold text-xl mb-2"><%= line_item.product.title %></h2>
                    <p class="font-bold mb-2"><%= number_to_currency(line_item.product.price) %></p>
                  <div class="mt-4 flex items-center gap-4">
                    <div class="flex items-center border border-gray-300 rounded overflow-hidden">
                      <span class="bg-gray-50 px-3 py-1 text-gray-600 text-sm border-r">Quantity:</span>
                      <input type="text" value="<%= line_item.quantity %>" class="w-12 text-center py-1" readonly>
                      <%= button_to "+", line_item_path({id:line_item.id, line_item: {quantity:line_item.quantity+1}}), method: :patch, class: "bg-gray-100 px-3 py-1 border-l text-gray-600 cursor-pointer" %>
                    </div>
                  </div>
                  <div class="mt-4">
                    <%= button_to "Remove", line_item_path(line_item), method: :delete, data: { confirm: "Are you sure?" }, class: "text-red-600 hover:underline" %>
                  </div>
              </div>
            <% end %>
        </div>
        <div class="lg:col-span-1">
      <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100 sticky top-4">
        <h3 class="text-lg font-bold mb-4 border-b pb-2">Order Summary</h3>       
        <div class="flex justify-between mb-2 text-gray-600">
          <span>Subtotal (<%= cart.line_items.sum(:quantity) %> items):</span>
          <span><%= number_to_currency(cart.total_price) %></span>
        </div>     
        <div class="flex justify-between mb-4 text-gray-600">
          <span>Tax:</span>
          <span>$0.00</span>
        </div>
        
        <div class="flex justify-between mb-6 text-xl font-bold text-gray-900 border-t pt-2">
          <span>Total:</span>
          <span><%= number_to_currency(cart.total_price) %></span>
        </div>

        <button class="w-full bg-emerald-800 hover:bg-emerald-900 text-white font-bold py-3 px-4 rounded shadow transition duration-200">
          Proceed to Checkout
        </button>
        
        <div class="mt-4">
           <%= button_to 'Empty Cart', cart_path(cart), method: :delete, class: "w-full bg-white border border-gray-300 text-gray-700 py-2 px-4 rounded hover:bg-gray-50 font-medium" %>
        </div>
      </div>
    </div>
      </div>
    <% else %>
        <p class="text-gray-600">Your cart is empty.</p>
    <% end %>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, class: "contents") do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul class="list-disc ml-6">
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<% content_for :title, "Editing cart" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Show this cart", @cart, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to carts", carts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/carts/index.html.erb
<% content_for :title, "Carts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Carts</h1>
    <%= link_to "New cart", new_cart_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="carts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @carts.any? %>
      <% @carts.each do |cart| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render cart %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", cart, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_cart_path(cart), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", cart, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No carts found.</p>
    <% end %>
  </div>
</div>

app/views/carts/modal.html.erb
<%= turbo_frame_tag "cart_modal_content" do %>
  <div class="flex h-full flex-col bg-gray-900 shadow-xl">
    
    <div class="flex items-start justify-between px-4 py-6 sm:px-6 border-b border-gray-700">
      <h2 class="text-lg font-medium text-white" id="slide-over-title">Your Cart</h2>
      <div class="ml-3 flex h-7 items-center">
        <button type="button" data-action="click->slideover#close" class="relative -m-2 p-2 text-gray-400 hover:text-gray-200">
          X
        </button>
      </div>
    </div>

    <div class="flex-1 overflow-y-auto py-6 px-4 sm:px-6">
      <% if (@cart.present? && @cart.line_items.any?) %>
        <ul role="list" class="-my-6 divide-y divide-gray-700">
          <% @cart.line_items.each do |line_item| %>
            <li class="flex py-6">
              <div class="h-20 w-20 shrink-0 overflow-hidden rounded-md border border-gray-700 bg-white p-1">
                 <%= image_tag line_item.product.image_url, class: "h-full w-full object-contain object-center" %>
                 <div class="h-full w-full bg-gray-100"></div>
              </div>

              <div class="ml-4 flex flex-1 flex-col">
                <div>
                  <div class="flex justify-between text-base font-medium text-white">
                    <h3><%= line_item.product.title %></h3>
                    <p class="ml-4"><%= number_to_currency(line_item.product.price * line_item.quantity) %></p>
                  </div>
                </div>
                <div class="flex flex-1 items-end justify-between text-sm">
                  <div class="flex items-center border border-gray-700 rounded overflow-hidden mt-2">
                     <%= button_to '-', line_item_path(line_item), method: :patch, params: { line_item: { quantity: line_item.quantity - 1 }, turbo_stream: "true" }, class: "px-3 py-1 text-gray-400 hover:bg-gray-800 hover:text-white cursor-pointer disabled:cursor-not-allowed", disabled: line_item.quantity <= 1 %>
                     <input type="text" value="<%= line_item.quantity %>" class="w-10 text-center py-1 bg-gray-900 text-white focus:outline-none border-x border-gray-700 text-sm" readonly>
                     <%= button_to '+', line_item_path(line_item), method: :patch, params: { line_item: { quantity: line_item.quantity + 1 }, turbo_stream: "true" }, class: "px-3 py-1 text-gray-400 hover:bg-gray-800 hover:text-white cursor-pointer" %>
                  </div>

                  <div class="flex">
                     <%= button_to 'Remove', line_item_path(line_item), method: :delete, params: { turbo_stream: "true" }, class: "font-medium text-indigo-400 hover:text-indigo-300 bg-transparent border-0 p-0" %>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-gray-400 text-center mt-10">Your cart is currently empty.</p>
      <% end %>
    </div>

    <div class="border-t border-gray-700 px-4 py-6 sm:px-6 bg-gray-900">
      <div class="flex justify-between text-base font-medium text-white">
        <p>Subtotal</p>
        <p><%= @cart ? number_to_currency(@cart.total_price) : "0.00" %></p>
      </div>
      <p class="mt-0.5 text-sm text-gray-400">Shipping and taxes calculated at checkout.</p>
      <% if @cart.present? %>
        <div class="mt-6">
          <%= link_to 'Show Cart', cart_path(@cart), data: { turbo_frame: "_top" }, class: "flex items-center justify-center rounded-md border border-transparent bg-white px-6 py-3 text-base font-medium text-gray-900 shadow-sm hover:bg-gray-100" %>
        </div>
      <% end %>
      <div class="mt-6 flex justify-center text-center text-sm text-gray-400">
        <p>
          or
          <button type="button" data-action="click->slideover#close" class="font-medium text-indigo-400 hover:text-indigo-300">
            Continue Shopping
            <span aria-hidden="true"> &rarr;</span>
          </button>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/new.html.erb
<% content_for :title, "New cart" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Back to carts", carts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/carts/show.html.erb
<% content_for :title, "Showing cart" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

    <h1 class="font-bold text-2xl mb-6 pb-2 my-5">Your Cart</h1>
    <%= render @cart %>
</div>