config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts

  root "store#index", as: "store_index"
  get "cart/modal", to: "carts#modal", as: :cart_modal
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> The Pragmatic Collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full flex flex-row bg-[#F2F0EF] min-h-screen h-full">      
    <ul class="w-[160px] bg-[#2C4A3B] flex flex-col text-white shadow-lg overflow-hidden h-100vh z-10">
      <li class="h-16 flex items-center px-6 border-b border-white/10 fixed top-0 bg-[#2C4A3B] z-10 w-[160px]">
            <h1 class="text-xl font-semibold tracking-wide">Pragmatic</h1>
      </li>

      <li class="hover:bg-[#3E6351] mt-25">
        <%= link_to "Home", store_index_path, class: "flex items-center px-4 py-2.5 bg-white/10 text-white rounded-md transition-colors" %>
      </li>
      <li>
        <a href="#" class="flex items-center px-4 py-2.5 text-gray-300 hover:bg-white/5 hover:text-white rounded-md transition-colors">
                <span class="text-sm font-medium">Questions</span>
        </a>
      </li>
      <li>
        <a href="#" class="flex items-center px-4 py-2.5 text-gray-300 hover:bg-white/5 hover:text-white rounded-md transition-colors">
            <span class="text-sm font-medium">News</span>
        </a>
      </li>
      <li>
        <a href="#" class="flex items-center px-4 py-2.5 text-gray-300 hover:bg-white/5 hover:text-white rounded-md transition-colors">
            <span class="text-sm font-medium">Contact</span>
        </a>
      </li>
    </ul>
    <div class="flex flex-col flex-1 min-h-screen">
      <header class="bg-white shadow-md h-16 content-center fixed top-0 z-10 w-[calc(100%-160px)]">
        <div class="w-full px-5 py-4 flex justify-end items-center">
          <nav>
            <ul class="flex space-x-4">
              <li><a href="#" class="text-gray-700 hover:text-gray-900">Login</a></li>
              <li><a href="#" class="text-gray-700 hover:text-gray-900">Register</a></li>
              <li>
                  <% if @cart&.persisted? %>
                   <a data-controller="slideover-trigger"
                      data-slideover-trigger-slideover-outlet="#cart-modal" 
                      data-action="click->slideover-trigger#open" >
                      <span>Cart</span>
                        <span id="cart-count">
                          <% if @cart && @cart.line_items.any? %>
                            <span>(<%= @cart.total_items %>)</span>
                          <% else %>
                            <span>(0)</span>
                          <% end %>
                        </span>
                    </a>
                  <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main class="w-full bg-[#F2F0EF] mx-auto px-3  md:px-5 pb-5 mt-20 h-full">
          <%= yield %> 
      </main>
    </div>
  <div id="cart-modal" data-controller="slideover" data-slideover-target="container" class="relative z-100 hidden" >
    
    <div 
      data-slideover-target="backdrop" 
      data-action="click->slideover#close"
      class="fixed inset-0 bg-gray-900/75 bg-opacity-75 transition-opacity duration-500 ease-in-out opacity-0"
    ></div>

    <div class="fixed inset-0 overflow-hidden pointer-events-none">
        <div class="absolute inset-0 overflow-hidden">
            <div class="pointer-events-none fixed inset-y-0 right-0 flex max-w-full pl-10">
                <div data-slideover-target="panel" class="pointer-events-auto w-screen max-w-md transform transition duration-500 ease-in-out translate-x-full sm:duration-700">
                    <%= turbo_frame_tag "cart_modal_content", src: cart_modal_path, loading: :lazy do %>
                        <div class="flex h-full flex-col bg-gray-900 p-6 text-white shadow-xl">
                            Loading...
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
  </body>
</html>